CREATE USER VALIDACAO IDENTIFIED EXTERNALLY;

GRANT CREATE SESSION,
	CREATE ANY TABLE,
	DROP ANY TABLE,
	ALTER ANY TABLE,
	CREATE ANY SEQUENCE,
	DROP ANY SEQUENCE,
	ALTER ANY SEQUENCE
TO VALIDACAO;
ALTER USER VALIDACAO QUOTA UNLIMITED ON SYSTEM;

-- Criar usuario de conexao no GETRAN
CREATE USER validacao_conexao IDENTIFIED BY validacao_conexao;
GRANT CREATE SESSION,
	CREATE ANY TABLE,
	DROP ANY TABLE,
	ALTER ANY TABLE,
	CREATE ANY SEQUENCE,
	DROP ANY SEQUENCE,
	ALTER ANY SEQUENCE
TO validacao_conexao;
ALTER USER validacao_conexao QUOTA UNLIMITED ON SYSTEM;

create table validacao.usuario (
	ID_USUARIO NUMBER(19) NOT NULL PRIMARY KEY,
	CLIENTE VARCHAR2(50 CHAR) NOT NULL CONSTRAINT UK_UNIQUE_CLIENTE UNIQUE,
    DATA_CADASTRO DATE DEFAULT SYSDATE);

CREATE TABLE VALIDACAO.REQUISICAO_PRECO(
    ID_REQUISICAO_PRECO NUMBER(19) NOT NULL PRIMARY KEY,
    PRECO NUMBER(10,2) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE
);

CREATE TABLE VALIDACAO.REQUISICAO (
    ID_REQUISICAO NUMBER(19) NOT NULL PRIMARY KEY,
    ID_USUARIO NUMBER(19) NOT NULL,
    ID_REQUISICAO_PRECO NUMBER(19) NOT NULL,
    RESULTADO NUMBER(1,0) NOT NULL,
    NUM_DOC VARCHAR2(20) NOT NULL,
    DATA_CADASTRO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USUARIO_ID FOREIGN KEY (ID_USUARIO) REFERENCES VALIDACAO.USUARIO,
    CONSTRAINT FK_REQUISICAO_PRECO_ID FOREIGN KEY (ID_REQUISICAO_PRECO) REFERENCES VALIDACAO.REQUISICAO_PRECO
);

CREATE PUBLIC SYNONYM REQUISICAO_PRECO FOR VALIDACAO.REQUISICAO_PRECO;
CREATE PUBLIC SYNONYM REQUISICAO FOR VALIDACAO.REQUISICAO;
CREATE PUBLIC SYNONYM usuario FOR validacao.usuario;

CREATE SEQUENCE VALIDACAO.USUARIO_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VALIDACAO.REQUISICAO_PRECO_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE VALIDACAO.REQUISICAO_SEQUENCE START WITH 1 INCREMENT BY 1;

GRANT ALL ON VALIDACAO.REQUISICAO_PRECO TO validacao_conexao;
GRANT ALL ON VALIDACAO.REQUISICAO TO validacao_conexao;
GRANT ALL ON validacao.usuario TO validacao_conexao;
GRANT ALL ON VALIDACAO.REQUISICAO_PRECO_SEQUENCE TO VALIDACAO_CONEXAO;
GRANT ALL ON VALIDACAO.REQUISICAO_SEQUENCE TO VALIDACAO_CONEXAO;
GRANT ALL ON VALIDACAO.USUARIO_SEQUENCE TO VALIDACAO_CONEXAO;

insert into requisicao_preco (id_requisicao_preco,data_inicio, preco) values (VALIDACAO.REQUISICAO_PRECO_SEQUENCE.nextval, sysdate, 0.10);

UPDATE requisicao_preco SET data_fim = sysdate where data_fim is null;


SELECT * FROM requisicao;
SELECT * FROM requisicao_preco;
SELECT * FROM USUARIO;

